source :rubygems

# A faster web server.
gem 'thin'

# Markdown rendering support for R18n and Tilt.
gem 'rdiscount'
gem 'maruku'

# Datamapper is nowhere without this.
gem 'dm-migrations'
gem 'dm-aggregates'

# Datamapper connection methods.
gem 'dm-mysql-adapter'
#gem 'dm-postgres-adapter'
#gem 'dm-sqlite-adapter'

# Some often used template utilities. Add/enable at will.
gem 'erubis'
# gem 'RedCloth'
# gem 'liquid'
# gem 'less'
