source :rubygems

# A faster web server.
gem 'thin'

# Markdown rendering support for R18n and Tilt.
gem 'rdiscount'
gem 'maruku'

# Datamapper is nowhere without this.
gem 'dm-aggregates'

# Some often used template utilities. Add/enable at will.
# gem 'RedCloth'
# gem 'liquid'
# gem 'less'
